language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - hhvm

script: phpunit --configuration phpunit.xml --coverage-text

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false